### ISSUE TITLE
Making SwinjectStoryboard inheritance friendly

### ISSUE THREAD

**Issue by VladimirBorodko** [Swinject/SwinjectStoryboard#13]
This is an enhancement request
In case of inheriting from SwinjectStoryboard There should be overridable method which accepts Container.Controller and ResolverType as parameters, so subclass could check for controller protocol conformance and alter resolve process.

use case:

```swift
protocol ViewModeleledView: NSObjectProtocol {
    associatedtype ViewModel
    var viewModel: ViewModel! {get set}
}
private protocol ViewModelResolvableView {
    func resolve(resolver: ResolverType)
}
private extension ViewModeleledView: ViewModelResolvableView  {
    func resolve(resolver: ResolverType) {
        viewModel = resolver. resolve(ViewModel.self)
   }
}
class AltStoryboard: SwinjectStoryboard {
    override func resolve(controller: Container.Controller, with resolver: ResolverType) {
        if let controller = controller as? ViewModelResolvableView {
            controller. resolve(resolver)
        } else {
            super. resolve(controller, with: resolver)
        }
    }
}
```

With this I can omit registration of ViewModeleledViews in container

**Comment by yoichitgy** [comment]
Hi @VladimirBorodko. Thank you for the request, but I think the usage of `resolve` is irregular because not a container but a controller invokes `resolve`. I think the API of SwinjectStoryboard is easier for most of users to understand without the `resolve` method with `Controller` and `ResolverType`.

SwinjectStoryboard is just an extension to Swinject. In your case, you can create your own SwinjectStoryboard-like class inheriting _SwinjectStoryboardBase or from scratch. The implementation is not so difficult if you see the code of SwinjectStoryboard😃

Anyway, thank you for your idea. It is a good finding for me to see how a user uses Swinject and SwinjectStoryboard👍
