### ISSUE TITLE
SwinjectStoryboard 1.0.0 doesn't work with Swinject 2.1.0

### ISSUE THREAD

**Issue by alinmuntean** [Swinject/SwinjectStoryboard#48]
Hello,
So I'm having a project written in Swift 3.1 and tried to add the Swinject and SwinjectStoryboard with Cocoapods like this:
```
pod 'Swinject', '~> 2.1.0'
pod 'SwinjectStoryboard', '~> 1.0.0'
```
I'm getting the following error when running "pod install". I'm guessing it's a compatibility issue.

```
[!] Unable to satisfy the following requirements:

- `Swinject (~> 2.1.0)` required by `Podfile`
- `Swinject (= 2.0.0)` required by `SwinjectStoryboard (1.0.0)`
```
Using Swinject 2.0.0 works fine, but I'm getting the 2 warnings regarding the 'initialize()' functions 🙂 (because of Swift 3.1).

Thanks,
Alin

**Comment by mpdifran** [comment]
You're getting this error because `SwinjectStoryboard` is requiring exactly `Swinject 2.0.0`. You'll have to use that version (`pod 'Swinject', '~> 2.0.0'`) until `SwinjectStoryboard` is updated to support `2.1.0`, or its requirements are loosened.

As for the warnings, we've got a W.I.P to fix them. Hopefully that makes it into `SwinjectStoryboard 1.1.0`.

**Comment by alinmuntean** [comment]
Thanks @mpdifran, that's how I currently use it 😄. Waiting for the new version.

**Comment by yoichitgy** [comment]
Released SwinjectStoryboard v1.1.0 to use with Swinject v2.0.0 or higher.
https://github.com/Swinject/SwinjectStoryboard/releases/tag/1.1.0

Actually @mpdifran fixed the issue by #43. Thank you very much😃😃😃

**Comment by alexisbronchart** [comment]
The `SwinjectStoryboard` release `1.1.0` only allows a higher _patch_ version of `Swinject`. The `~>` operator works based on the last component that you specify in your version requirement (check [the documentation](https://guides.cocoapods.org/syntax/podfile.html#pod)). So if the goal was to make it work with Swinject 2.1.0 you should specify `s.dependency 'Swinject', '~> 2.0'` in the podspec (not `~>2.0.0`). Unless this was intentional?

**Comment by mpdifran** [comment]
Ah you're right, I was thinking of Carthage where it allows a higher *minor* even when you specify `~> 2.0.0`.

**Comment by yoichitgy** [comment]
I'm fixing now, thanks @alexisbronchart!

**Comment by yoichitgy** [comment]
Fixed👍 Thanks @alexisbronchart!

@mpdifran, yeah, I also had misunderstanding that Carthage and CocoaPods work in the same way to specify the version.
